Version id 3850 stable

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,185 +1,140 @@
-# ANTsRCore Build
 language: r
-sudo: false
-cache:
-  - timeout: 1000
-  - packages
 warnings_are_errors: true
-bioc_required: false
+cache: packages
+use_bioc: true
+bioc_required: true
 cran: http://cran.rstudio.com
-dist: xenial
-
+dist: trusty
+addons:
+  apt:
+    packages:
+    - libcurl4-openssl-dev
+    - libxml2-dev
+    - libfftw3-dev
+    - libgsl0-dev
+    - libgsl0ldbl
+    - mesa-common-dev
+    - libglu1-mesa-dev
+    - devscripts
 os:
-  - linux
-  - osx
-
-# as xenial
+- linux
+- osx
+osx_image: xcode9.4
 services:
-  - xvfb
-
+- xvfb
 r:
-  - oldrel
-  - release
-  - devel
-
+- 3.3
+- 3.4
+- 3.5
+- release
+- devel
 matrix:
   allow_failures:
-    - r: devel
-    - os: osx
-    - os: windows
-
-latex: false
-compiler: clang
-osx_image: xcode9
-
+  - r: devel
 env:
   global:
-  - R_BUILD_ARGS=" --no-build-vignettes --no-manual "
-  - R_CHECK_ARGS=" --timings --as-cran --no-manual --no-vignettes --install-args=--build"
+  - R_BUILD_ARGS="--no-manual"
+  - R_CHECK_ARGS="--as-cran --install-args=--build"
   - RGL_USE_NULL=TRUE
-  - R_CHECK_TIME="TRUE"
-  - R_CHECK_TESTS="TRUE"
-  - _R_CHECK_TIMINGS_="0"
-  - _R_CHECK_FORCE_SUGGESTS_=false
-  - BOOTSTRAP_LATEX=1
+  - WARNINGS_ARE_ERRORS=1
+  - PROJECT_NAME=neuroconductor-releases
   - DISPLAY=:99.0
-
+  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
+  - _R_CHECK_FORCE_SUGGESTS_=false
+  - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
 before_install:
-  - ulimit -n 2048
-  - export ANTS_RANDOM_SEED=123
-  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
-  - export PROJ_DIR=`basename ${TRAVIS_BUILD_DIR}`
-  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
-  - fname=travis_helpers.sh
-  - wget -O ${fname} http://bit.ly/travis_helpers
-  - cat ${fname}; source ${fname}; rm ${fname}
-  - codename=`linux_codename`;
-  - if [ "${codename}" = "trusty" ];
-    then
-      start_xvfb ;
-    fi
-  - export rver=`r_version`;
-  - export gh_user=`get_gh_user` ; echo $gh_user ;
-  - cat DESCRIPTION
-  - export PACKAGE_NAME=`package_name`
-  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
-  # does all the clang exports
-  - x=`export_clang_cxx`; eval ${x}
-  - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then
-      no_open_mp ;
-    fi
-  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
-  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
-  - clang_cxx
-  # - hdf5_install ;
-  - export cmake_version="3.14"
-  - cmake --version
-  - x=`cmake_setup`; echo "${x}"; eval ${x};
-  - cmake --version
-  - ./cleanup
-  - Rscript -e "install.packages( c('Rcpp', 'RcppEigen'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
-  - Rscript -e "install.packages( c('magrittr','testthat','knitr','rmarkdown','covr','devtools', 'desc',  'remotes', 'colormap' ), repos=c(CRAN='https://cran.rstudio.com'))"
-  - cd ..
-  - git clone https://github.com/muschellij2/ghtravis.git
-  - R CMD INSTALL ghtravis
-  - cd ANTsRCore
-  # - if [[ "${gh_user}" == "muschellij2" ]]; 
-  #   then 
-  #     gh_binary_install muschellij2/ITKR ;
-  #   else 
-  #     gh_binary_install stnava/ITKR ;
-  #   fi
-  - gh_binary_install stnava/ITKR ;
-  - export ants_user=ANTsX
-#  - install_missing_remote_deps ${ants_user}/ANTsRCore
-#  - echo "Done Installing Missing Deps"
-#  - cat DESCRIPTION
-#  - install_remotes_no_dep
-#  - cat DESCRIPTION
-#  - echo $PATH ;
-#  - install_deps_all
-
-
-install:
-  - echo 'skip this'  # travis was forcing installs here via devtools
-
+- ulimit -n 2048
+- export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
+- export PROJ_DIR=`basename $PWD`
+- echo "travis_wait*\.log$" >> .Rbuildignore
+- fname=travis_helpers.sh
+- wget -O ${fname} http://bit.ly/travis_helpers
+- cat ${fname}; source ${fname}; rm ${fname}
+- cat DESCRIPTION
+- start_xvfb ;
+- jags_install || true;
+- if `need_v8`; then v8_install || true; fi
+- dcmtk_install || true;
+- gsl_install 2.1 || true ;
+- export rver=`r_version`; echo $rver ;
+- export PACKAGE_NAME=`package_name`
+- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+- remove_neuroc_packages
+- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
+- x=`export_clang_cxx`; eval ${x}
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; brew install -v freetype ; fi
+- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
+- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+- clang_cxx
+- export cmake_version="3.11"
+- cmake --version
+- x=`cmake_setup`; echo "${x}"; eval ${x};
+- cmake --version
+- export ants_user=neuroconductor-releases
+- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}"
+  == "ANTsR" ]]; then Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type =
+  'source', repo = 'http://cran.rstudio.com')" ; fi
+- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]]; then export
+  R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ; export R_CHECK_ARGS="--no-vignettes
+  ${R_CHECK_ARGS}" ; fi
+- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ITKR" ;
+  install_missing_remote_deps_all ${ants_user}/ITKR ; gh_binary_install ${ants_user}/ITKR
+  ; fi
+- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
+  "Installing Missing Deps ANTsRCore" ; install_missing_remote_deps_all ${ants_user}/ANTsRCore;
+  gh_binary_install_passive ${ants_user}/ANTsRCore ; fi
+- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}"
+  != "ANTsR" ]]; then echo "Installing Missing Deps ANTsR" ; install_missing_remote_deps_all
+  ${ants_user}/ANTsR ; gh_binary_install_passive ${ants_user}/ANTsR ; fi
+- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false
+  ; fi
+- cat DESCRIPTION
+- install_remotes_no_dep
+- cat DESCRIPTION
+- echo $PATH ;
+- install_deps_no_suggests
+- install_python_requirements ;
+- R CMD javareconf ;
+- travis_run_cache
 script:
-  - x=`export_clang_cxx`; eval ${x}
-  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
-  - rm -f travis_wait*.log
-  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
-  - ls
-  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
-  - rm -f travis_wait*.log
-  - if [[ $CHECK_RET -ne 0 ]];
-    then
-      echo "R CMD check failed";
-      check_fail;
-      dump_logs;
-      check_warnings ;
-      travis_terminate 1;
-    fi
-
-after_failure:
-  - dump_logs
-
+- x=`export_clang_cxx`; eval ${x}
+- travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+- rm -f travis_wait*.log
+- PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+- ls
+- travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+- rm -f travis_wait*.log
+- if [[ $CHECK_RET -ne 0 ]]; then echo "R CMD check failed"; check_fail; dump_logs;
+  travis_terminate 1; fi
+- check_warnings
 after_success:
-  - dump_logs
-  - ls
-  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
-  - PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
-      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);
-      PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
-    fi
-  - mv ${PKG_FILE_NAME} ${PKG_TARBALL_WITH_R} ;
-  - PKG_FILE_NAME=${PKG_TARBALL_WITH_R}  ;
-
-notifications:
-  email:
-    recipients:
-    - stnava@gmail.com
-    on_success: change
-    on_failure: always
-
-# so no overwrite of linux build
+- dump_logs
+after_failure:
+- dump_logs
 before_deploy:
-  - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then
-      rm -f *.tar.gz;
-    fi
-
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
+  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
+  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
+- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
+  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
+  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
+  ; fi
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -f *.tar.gz; fi
 deploy:
-  - provider: releases
-    api_key:
-      secure: Hm3kbkCySSneOe8644MWudbNAphB4+YDpGhWCeeHuSiHoQU6+Qmx/f014iVM5JqZI72EGX21hSygqfD9jB8O78J4imO4xMUnNciA80pV/NlUnzwMiYVfpYAga3QQApvSJZuBA/4+kJXlFZkigWGXuzb8W5Qty0xY1KV9FuaUzo5bRxCPa4f3t3PP/Ikjhla2vH53UHo+YiRIfGlH5Rn3p2kDS5390cfdO5+1kn8p5UMZV7C1B2VAE2OO0QxtVmjZbpAxE/k+QGdeGMXBfu5bCfERO3Wr/sfITaTu9j5Oulv/fDfVe6kuIRhAkX0eUn+CEkEhBgSO6yp1+abcagxIRVYfF3hp5e6+cOeGC/QH0z9kSsCim3SdYvz+rFhtzS+vO4LTO8wgGzyMLalvH2Jopf4OrRbSwbmiLpQzR/fFrmx9IZt0o4lD9+KW9Nhj0o9+V6NHg+Usx1wbTVYDjh53op6AT5c6E4Zej0gLeG9gXXtICtcEE1pCLiK8EX11cCUpgRD0NcG+F/dcPY5kLtf4/Uw/krhwz8OagPk9Mt3aleu0iepkuwQoGNoy2XBzc0zcaGICC3Y23KW/VZRc0xZGjiUmQXyMlbuB/dOYr0V8VGVPanRgDksr+ML0B4nqdfbtqTC1FQl2ORtG7iCDuArAZo7bokisZ2GTSA2F85BpfRY=
-    file: ${PKG_FILE_NAME}
-    skip_cleanup: true
-    on:
-      tags: true
-      repo: ${gh_user}/${PROJ_DIR}
-      all_branches: true
-      condition: "${gh_user} = ANTsX"
-  - provider: releases
-    api_key:
-      secure: TEYRCpA1JpjgYc/KbcuKMcMvclFPYkUxr0lv1s6j/VBZkwIBd4e8/1uTXUeP6EfwN97XI+Y9X/v2t/Bp3VgsJVSbvicVFvz8EHSUvY16tiyQbZAxbfo8zljFUSegPGN8cuHnjIULI5mrKAb997QN4+VfTdccvcjwCldO/Nk52Df7IuYYqzFBoSa11RwRveSR2+fHqHE48l+fX2SUwtILXJLoG8F2urbJ9HmuTslHPVcVJ+D6X5JOUCzVvSGepo8i+V3ULQqLE9OkckoigS0DoJtCqgj2YqzX+n6edUrjoOoaA5p/f/m+WhWrUuKXBVKBeWkHw7Qv+V7tWajdRvPLv3gZY9xARSkZ90ZN8MiIbYpyX4IAN63pcZiC9fCwrV0loS21z0/SgLmQQvqkpB0MtU17Pk0IznbIqLQ2jXX9LUDSGN9z1Aa+culEAyP72nbhqdcMFtzm/kUhZ7ysVs2/55Kj6Sh/NEd0KILbaVZeOx20/mxWDrhwhRHiESKloG97hqDBqCnd7LNRWqHS6/49kD33+ZZl2MTbzpPefNcsAJc5qI2wPAq90n4RZfaxdr+sMmKWUq85+mhzvKNushLhj6hXG055vvO+KgasmGBAO9n1l1tz7UyAZjgifunj6HprLry0mxCifZvOpM3vTxOSl9COfKR59OyjhfuAVWcX5L4=
-    file: ${PKG_FILE_NAME}
-    skip_cleanup: true
-    on:
-      tags: true
-      repo: muschellij2/ANTsRCore
-      all_branches: true
-      condition: "${gh_user} = muschellij2"
+  provider: releases
+  skip_cleanup: true
+  file_glob: true
+  overwrite: true
+  file: "${PACKAGE_NAME}*.t*gz"
+  on:
+    tags: true
+  api-key:
+    secure: ZBGeiBU0yjkYpGLfXonALGB/vbdM3HnGjBWQg7hjAtsI9gtSq/g7asGy0BvEtdMcPIfHwbq/AyIwngVtNMXvgbgEUWhEF+FcckfPg9KeBG/xTywd6hw+t35XWM3U6ZfuzvCHWPtBHWwFHpK7iyyEFUo/UpfoQFSP8tlQc/lPPZhnBYpvJtqQm4a6k6u8SkkmjPR5+Z8KsjJ1cShkvf051XGmaA9UHViO56W+hOy04GLFqjcXn0LkXg6HlGav1cXWC3E/ZfSTlyRlWCyc1GNEcbzZHY/k/otdfBex6olpPUqcBROhPunvwXP3UUZGNRMgqdIwQ60Bahwwb9PBKAEHNn2yeAl1u+oZBwdJykisKst5FuFA6vP/ByE3T6odJmsDP18eKwFSnmVZOmSe2U+0Nfs1sA09wbVO2yZKjvefVhusrsrIo9uwGhI71c0/RLctpbmFqqU1sHnqfiApBlw0B5zCMcg1nYbJ414uHjOvDuaxrY6WNOdZIE+15+E3mFO2Fxuau0KJzFypJpKgavuAZ2bYDvQNbZQPyZsKrQ7V1Jt7r4+D9FmAkaRA0mD/FdeaC+2x9KmF32bcXGSmxdu/zTqpbenR0+p1sMlupMeK9PdxsYRMQfXg64jJOg8uT8uML49DJCIqEhM+ZB2kbXxLabXw60NikCeyteiEsFYJNLQ=
+after_deploy:
+- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
+  else run_coverage=; fi;
+- if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then echo 'covr::coveralls(type
+  = "all", quiet = FALSE)' > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R
+  ; rm neuroc_covr.R ; fi
 
-  # - provider: releases
-  #   api_key:
-  #     secure: S6aYhOkDea+5abwE3x035WAW+LFgJnvPCwDTxILryNaifdtd/WoQvdW9RB39ZokDVMiXkxyyT1aXZFksUO2hDyxtkOTLdesNj9IKbd0Lea/L67mJI8yvrRUYzKSAEE5n6/4QsMUs9RIxzi32S0i8UlH0UAG8+QPwTfYWUMiSXVJPUIi4gcwQ3xRUyQ5/Ixs0ZizpcuKHgW7uoa0ZqeoPz1aFCEniIvfeDYcdp3oHRsCuAvqPhrBKuioyAyWGH4BvNF7poON6gYBP3bGKWpG/Z21263OrBaH14uItFdBdMuencZ1357nudrraITw1RLNMIeIzJ7Zf7G5RI/3BHPieg193eQGQGlwKT43jsPt6CHyq26qcgI9I4R+m7y8bjefL5H1Xd8Czt5sLw0Csdg2VBZ3OkGvI6WSk448kp89bpBoPrdtwkWBvf643pMdIz3ynxl1+Dc/RO3M2IvMSQIcmqkLDU6NpKcMUARmbcNR77xylsw1QWw/ndl3QtjS3upbUTeq6olhlW245+/soVDpgnIfW/betpJa6UPeWtAs3P8RnY1eJtrKNJCHm9sQDUM8+WuSkgJOApAVEnn4jdsClkWEXciT1wv7xzsOzs5gIXK4fNAN8crTJdYFdtjOZbPlEfPGGF61l+ty8hdsgT2cnQ9owNFRYj/ehTrcPK0ZrgJs=
-  #   file: ${PKG_FILE_NAME}
-  #   skip_cleanup: true
-  #   on:
-  #     tags: true
-  #     repo: ${gh_user}/${PROJ_DIR}
-  #     all_branches: true
-  #     condition: $gh_user = "muschellij2"
-
+#neuroc.deps version (SHA): 68c8a14
